language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - rbx-19mode

env:
  - "strong_parameters=0.2.0"
  - "strong_parameters=0.2.1"
  - "activesupport=3.2.13"
  - "activesupport=4.0.0"